# Generated by Django 5.2.4 on 2025-07-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=70)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_contact', models.IntegerField()),
                ('stu_image', models.ImageField(upload_to='image/')),
                ('stu_resume', models.FileField(upload_to='resume/')),
                ('stu_password', models.CharField(max_length=50)),
                ('stu_cpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
