# Generated by Django 5.2.4 on 2025-07-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=70)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_query', models.EmailField(max_length=70)),
            ],
        ),
    ]
