# Generated by Django 5.2.4 on 2025-07-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu_resuem',
            new_name='stu_resume',
        ),
    ]
