# Generated by Django 5.2.4 on 2025-08-08 09:53

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='image/')),
                ('vidio', models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='file/')),
                ('audio', models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='file/')),
            ],
        ),
    ]
