# Generated by Django 5.2.5 on 2025-08-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_image_alter_student_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
