# Generated by Django 5.2.4 on 2025-07-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adharnumber', models.IntegerField()),
                ('created_by', models.CharField()),
                ('created_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Adhar',
                'db_table': 'Adhar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('adharnumber', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='StudentInfo', to='app.adhar')),
            ],
        ),
    ]
