# Generated by Django 5.2.4 on 2025-07-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_department_student1'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=50, unique=True)),
                ('fuel_name', models.ManyToManyField(related_name='vehical', to='app.fuel')),
            ],
        ),
    ]
