# Generated by Django 5.2.4 on 2025-07-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_city', models.CharField()),
                ('e_contact', models.IntegerField()),
            ],
        ),
    ]
